### ISSUE TITLE
Graylog 3.3

### ISSUE THREAD

**Issue by space4u** [yon2004/GraySquid#2]
Hello,
i would like use the GraySquid Pack in Graylog 3.3.
The problem is, i can´t import it.

Herr the error messages:

java.lang.IllegalArgumentException: Unsupported content pack version: 0
	at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:101) ~[graylog.jar:?]
	at org.graylog2.rest.resources.system.contentpacks.ContentPackResource.installContentPack(ContentPackResource.java:293) ~[graylog.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.j

**Comment by yon2004** [comment]
Can you try the new version of the content pack and let me know if it works for you. If you find any bugs please let me know there is bound to be many.

**Comment by space4u** [comment]
Hi yon2004,

thanks for the very fast response.
The import works and the input is running. But i can´t see logs.

Docker shows the following message:
2020-10-01 19:44:04,170 ERROR: org.graylog2.plugin.inputs.transports.AbstractTcpTransport - Error in Input [Syslog TCP/5f762957627061245a2565f0] (channel [id: 0xe5637205, L:/172.20.0.2:19302 ! R:/172.20.0.6:47476]) (cause io.netty.handler.codec.DecoderException: java.lang.NumberFormatException: For input string: "1601581444.168")

My squid config is:
access_log tcp://graylog:19302 squid

regard :)

**Comment by space4u** [comment]
Hello yon2004,
I believe, one error is the ^ symbol in line 246 and some missing spaces between the argument?
I have try to fix it, but no success.

regards

**Comment by yon2004** [comment]
I'm sorry but I could not tell you why it is not working. I have only tested it with a syslog forwarder possibly give that a try.
